package com.example.generator;
import org.springframework.boot.*; import org.springframework.boot.autoconfigure.SpringBootApplication; import org.springframework.context.annotation.Bean; import org.springframework.web.client.RestClient; import tools.jackson.databind.JsonNode; import java.util.*;
@SpringBootApplication public class DataGeneratorApplication {
 public static void main(String[] a){SpringApplication.run(DataGeneratorApplication.class,a);}
 @Bean CommandLineRunner generate(RestClient.Builder b){return args->{var customer=client(b,"CUSTOMER_SERVICE_URL","http://localhost:8081"); var invoice=client(b,"INVOICE_SERVICE_URL","http://localhost:8084"); var adjustment=client(b,"INVOICE_ADJUSTMENT_SERVICE_URL","http://localhost:8087"); var payment=client(b,"PAYMENT_SERVICE_URL","http://localhost:8085"); var identity=client(b,"IDENTITY_SERVICE_URL","http://localhost:8086"); int count=Integer.parseInt(env("EVENT_COUNT","100")); var countries=List.of("PL","DE","GB","US","FR"); for(int i=0;i<count;i++){String email="customer-"+UUID.randomUUID()+"@example.com"; JsonNode c=post(customer,"/api/customers",Map.of("email",email,"fullName","Generated Customer "+i,"countryCode",countries.get(i%countries.size()))); String customerId=c.path("id").asText(); post(identity,"/api/identities",Map.of("customerId",customerId,"login",email)); JsonNode inv=post(invoice,"/api/invoices",Map.of("customerId",customerId,"amount","99.99","currency","EUR")); String invoiceId=inv.path("id").asText(); if(i%3==0) post(adjustment,"/api/invoice-adjustments",Map.of("invoiceId",invoiceId,"amount","10.00","currency","EUR","reason","Demo credit")); post(payment,"/api/payments",Map.of("invoiceId",invoiceId,"amount",i%3==0?"89.99":"99.99","currency","EUR","idempotencyKey","generated-"+i));}};}
 private static RestClient client(RestClient.Builder b,String key,String fallback){return b.clone().baseUrl(env(key,fallback)).build();}
 private static JsonNode post(RestClient c,String uri,Object body){return c.post().uri(uri).body(body).retrieve().body(JsonNode.class);}
 private static String env(String key,String fallback){return System.getenv().getOrDefault(key,fallback);}
}
