package com.example.semantic.query;
import com.example.semantic.model.*; import org.springframework.stereotype.Component; import java.util.*;
@Component public class QueryCompiler {
 private final CatalogService catalogs; public QueryCompiler(CatalogService catalogs){this.catalogs=catalogs;}
 public CompiledQuery compile(SemanticQuery request){var model=catalogs.model(request.model());var dimensions=indexDimensions(model);var metrics=indexMetrics(model);var select=new ArrayList<String>();var group=new ArrayList<String>();var columns=new ArrayList<CompiledQuery.Column>();var selected=new HashSet<String>();
  for(String name:request.dimensions()){var d=required(dimensions,name,"dimension");select.add("f."+d.column()+" as "+name);group.add("f."+d.column());columns.add(new CompiledQuery.Column(name,d.label(),d.type()));selected.add(name);}
  if(request.timeDimension()!=null){var d=required(dimensions,request.timeDimension().name(),"time dimension");if(!d.type().equals("time"))throw new IllegalArgumentException(d.name()+" is not a time dimension");String alias=d.name()+"_"+request.timeDimension().grain();String expression="date_trunc('"+request.timeDimension().grain()+"',f."+d.column()+")";select.add(expression+" as "+alias);group.add(expression);columns.add(new CompiledQuery.Column(alias,d.label()+" ("+request.timeDimension().grain()+")","time"));selected.add(alias);}
  for(String name:request.metrics()){var m=required(metrics,name,"metric");select.add(m.expression().replace("{table}","f")+" as "+name);columns.add(new CompiledQuery.Column(name,m.label(),m.type()));selected.add(name);}
  var where=new ArrayList<String>();var params=new LinkedHashMap<String,Object>();int i=0;for(var filter:request.filters()){var d=required(dimensions,filter.dimension(),"filter dimension");String key="p"+(i++);String op=switch(filter.operator()){case "eq"->"=";case "gte"->">=";case "lte"->"<=";case "in"->"in";default->throw new IllegalArgumentException("Unsupported operator");};if(op.equals("in")){where.add("f."+d.column()+" in (:"+key+")");params.put(key,filter.values());}else{if(filter.values().size()!=1)throw new IllegalArgumentException(filter.operator()+" requires one value");where.add("f."+d.column()+" "+op+" :"+key);params.put(key,filter.values().getFirst());}}
  var sql=new StringBuilder("select ").append(String.join(",",select)).append(" from ").append(model.source()).append(" f");if(!where.isEmpty())sql.append(" where ").append(String.join(" and ",where));if(!group.isEmpty())sql.append(" group by ").append(String.join(",",group));if(!request.orderBy().isEmpty()){var order=new ArrayList<String>();for(var o:request.orderBy()){if(!selected.contains(o.field()))throw new IllegalArgumentException("Order field must be selected: "+o.field());order.add(o.field()+" "+o.direction().toLowerCase());}sql.append(" order by ").append(String.join(",",order));}sql.append(" limit :resultLimit");params.put("resultLimit",request.limit());return new CompiledQuery(sql.toString(),params,columns);
 }
 private Map<String,SemanticCatalog.Dimension> indexDimensions(SemanticCatalog.Model m){var r=new HashMap<String,SemanticCatalog.Dimension>();m.dimensions().forEach(v->r.put(v.name(),v));return r;}
 private Map<String,SemanticCatalog.Metric> indexMetrics(SemanticCatalog.Model m){var r=new HashMap<String,SemanticCatalog.Metric>();m.metrics().forEach(v->r.put(v.name(),v));return r;}
 private <T>T required(Map<String,T> values,String name,String type){var v=values.get(name);if(v==null)throw new IllegalArgumentException("Unknown "+type+": "+name);return v;}
}
